### ISSUE TITLE
Warbler should be using load instead of require to load *.class files

### ISSUE THREAD

**Issue by sanelson2000** [jruby/warbler#102]
Currently, in jruby-1.7.0.preview1, you must manually go in and change all of the require statements to load statements in order for it to find the class file.  According to @headius there are also performance gains to be had from switching to load as well.
See these related issues:
https://jira.codehaus.org/browse/JRUBY-6731
https://github.com/jruby/jruby-rack/issues/111#issuecomment-6691702

**Comment by kares** [comment]
seems it's been [using](https://github.com/jruby/warbler/blob/v1.4.0/lib/warbler/jar.rb#L62) `load` for a while now (at least since 1.4)
