### ISSUE TITLE
Creating Standalone .Jar file 

### ISSUE THREAD

**Issue by carlskii** [jruby/warbler#103]
Hi I've been struggling with this for some time. 

My Application structure is:-

      myapp
            |---app
                 |--main_app.rb
            |---bin
                 |--required_file1
                 |--required_file2              
            |---lib
                 |--library1.jar
                 |--library2.jar
                 |--library3.jar

If I use warbler to create standalone .jar I can see that it contains all of the required files in the correct directories. If I run the .jar file from the directory in which it was compiles everthing works as expected. 

However, If I move the .jar file to a different directory and run it, I get the following error:

java -jar CAPI-Dist.jar

gem install jruby-openssl for full support.
LoadError: no such file to load -- bin/required_file1

**main_app.rb**
```ruby
require "java"
require "openssl"
require "bin/required_file1"
require "bin/required_file2"
require 'library1.jar.jar'
```
**required_file1**
```ruby
require 'java'
require 'lib/library2.jar'
require 'lib/library3.jar'

```

What is the best way to configure this type of application?

**Comment by kares** [comment]
Warbler these days sets GEM_HOME for isolation. there's nothing it can do if loading .jars is not compliant.
