### ISSUE TITLE
warble aborted! stack level too deep

### ISSUE THREAD

**Issue by headius** [jruby/warbler#106]
(Moved here from http://jira.codehaus.org/browse/JRUBY-6412)

Warbler has given me this error intermittently in the past, but yesterday and today, I can't get past it.

I can't reproduce this on a fresh new Rails project, unfortunately, it's just my existing app that's having problems.

Stack trace and files to reproduce here: https://gist.github.com/f7c8a272189634386e93

**Comment by jkutner** [comment]
This is fixed with following environment:

```
$ jruby -v 
jruby 9.0.1.0 (2.2.2) 2015-09-02 583f336 Java HotSpot(TM) 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 [darwin-x86_64]

$ bundle version
Bundler version 1.10.6

﻿﻿$ gem list warbler

*** LOCAL GEMS ***

warbler (2.0.0.rc1)
```

Probably fixed in other versions too.

**Comment by SUDHARSHAN99** [comment]
I am getting the following error  while  creating test app when   executing "bundle exec rake test_app" command .
help me to solve this ....!

Expected string default value for '--rc'; got false (boolean)
/home/sudharshan/.rvm/gems/ruby-2.4.0@store_front/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
/home/sudharshan/.rvm/gems/ruby-2.4.0@store_front/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
/home/sudharshan/.rvm/gems/ruby-2.4.0@store_front/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/home/sudharshan/.rvm/gems/ruby-2.4.0@store_front/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
Generating dummy Rails application...
rake aborted!
SystemStackError: stack level too deep
/home/sudharshan/.rvm/gems/ruby-2.4.0@store_front/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:124:in `block (2 levels) in <class:Numeric>'
