### ISSUE TITLE
Support relative :path gems from Gemfile

### ISSUE THREAD

**Issue by bjeanes** [jruby/warbler#143]
I think it should be possible to support *some* `:path` gems from `Gemfile`s. If I understand correctly why it isn't supported now, it's because it would require rewriting the Gemfile to adjust the path of the gems. 

However, if we can determine from `Bundler::Source::Path` that the path is inside the project (e.g. `vendor/gems`), it should be possible to let through, no?

Unless I'm missing something huge, I might give this a stab when done with #141...

**Comment by kares** [comment]
even under vendor/gems it still would require rewriting - cause referencing might not work exactly the same in a .war. also supporting "only" relative paths under vendor/gems would be a little weird to say the least :)

**Comment by kares** [comment]
... stand corrected - for relative path it might work and is actually supported since 2.0.1
