### ISSUE TITLE
War fails on apache-tomcat-6.0.24 with latest version of Rails-3.2.12, ruby-2.0 and warbler-1.3.6

### ISSUE THREAD

**Issue by mukeshsinghr** [jruby/warbler#145]
I have created war file using warbler gem. When i deploy war file in apache-tomcat-6.0.24 server. After deployment, I am able to access rails default public page(my app home page). If I am trying to access any other pages I am getting following error. 

--- Backtrace
LoadError: load error: openssl -- java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERBoolean
                   require at org/jruby/RubyKernel.java:1027
                   require at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251
           load_dependency at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236
                   require at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251
                    (root) at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/rack-1.4.5/lib/rack/session/cookie.rb:1
                   require at org/jruby/RubyKernel.java:1027
                   require at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251
           load_dependency at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236
                   require at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251
                    (root) at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/actionpack-3.2.12/lib/action_dispatch/middleware/session/cookie_store.rb:1
                 const_get at org/jruby/RubyModule.java:2592
                    (root) at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/actionpack-3.2.12/lib/action_dispatch/middleware/session/cookie_store.rb:4
                    (root) at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/application/configuration.rb:1
                       tap at org/jruby/RubyKernel.java:1771
             session_store at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/application/configuration.rb:140
  default_middleware_stack at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/application.rb:273
  default_middleware_stack at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/application.rb:237
             instance_exec at org/jruby/RubyBasicObject.java:1738
                       app at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/engine.rb:469
                  Finisher at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/application/finisher.rb:31
                      each at org/jruby/RubyArray.java:1613
                       run at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/initializable.rb:30
          run_initializers at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/initializable.rb:55
                  __send__ at org/jruby/RubyBasicObject.java:1677
                      send at org/jruby/RubyKernel.java:2103
          run_initializers at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/initializable.rb:54
               initialize! at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/application.rb:136
                   require at org/jruby/RubyKernel.java:1027
            method_missing at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30
                    (root) at E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/config/environment.rb:5
                    (root) at file:/E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.1-lib-jruby-rack-1.1.13.1.jar!/jruby/rack/rails/environment3.rb:1

--- RubyGems
Gem.dir: E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems
Gem.path:
E:/Mukesh/Red Hat/Enterprise Web Server/share/apache-tomcat-6.0.24/webapps/war-demo/WEB-INF/gems
Activated gems:
  bundler-1.3.1
  rake-10.0.3
  i18n-0.6.4
  multi_json-1.7.1
  activesupport-3.2.12
  builder-3.0.4
  activemodel-3.2.12
  erubis-2.7.0
  journey-1.0.4
  rack-1.4.5
  rack-cache-1.2
  rack-test-0.6.2
  hike-1.2.1
  tilt-1.3.6
  sprockets-2.2.2
  actionpack-3.2.12
  mime-types-1.21
  polyglot-0.3.3
  treetop-1.4.12
  mail-2.4.4
  actionmailer-3.2.12
  arel-3.0.2
  tzinfo-0.3.37
  activerecord-3.2.12
  activeresource-3.2.12
  coffee-script-source-1.6.2
  execjs-1.4.0
  coffee-script-2.2.0
  rack-ssl-1.3.3
  json-1.7.7
  rdoc-3.12.2
  thor-0.17.0
  railties-3.2.12
  coffee-rails-3.2.2
  jquery-rails-2.2.1
  jruby-jars-1.7.3
  jruby-rack-1.1.13.1
  rails-3.2.12
  rubyzip-0.9.9
  sass-3.2.7
  sass-rails-3.2.6
  uglifier-1.3.0
  warbler-1.3.6

Please help me if i am missing any thing. If  anymore details required please let me know.

**Comment by kares** [comment]
as @mkristian noted - latest jruby-openssl is working without the need to hack/use the bouncy-castle gem.
