### ISSUE TITLE
Set listen hostname?

### ISSUE THREAD

**Issue by colindean** [jruby/warbler#181]
I've packaged a Sinatra app into a standalone, executable jar. I'm using winstone as the webserver.

**Is it possible to configure the webserver to listen only on localhost?**

 I would assume that this is configurable in web.xml, but I can't seem to find documentation on Google that indicates what must be present. My limited experience with WAR-style apps leads me to believe that perhaps this is best off in server.xml, but I'm not sure if that's right, right, nor am I sure exactly of what would go in server.xml.

**Comment by jazzido** [comment]
+1 to this. I've tried specifying my own `webserver.properties` in `config.webinf_files`, but seems it's being overwritten [here](https://github.com/jruby/warbler/blob/e593d7ff080ea5e1cdf4f69ae5f9eb471643b68b/lib/warbler/web_server.rb#L133)

**Comment by jkutner** [comment]
Warbler now supports the `warbler.host` system property. You can set like `-Dwarbler.host=0.0.0.0`.

**Comment by colindean** [comment]
:+1: :beers:
