### ISSUE TITLE
rake spec needs ant installed on the system

### ISSUE THREAD

**Issue by mkristian** [jruby/warbler#213]
since I did not read it in the README.md or so but without ant installed I see

 $ jruby -S rake spec
rake aborted!
Cannot run program "ant" (in directory "/home/christian/projects/active/maven/warbler"): error=2, No such file or directory
org/jruby/RubyIO.java:4073:in `popen'
org/jruby/RubyKernel.java:1054:in `require'
/home/christian/projects/active/maven/warbler/Rakefile:1:in `(root)'
org/jruby/RubyKernel.java:1073:in `load'
/home/christian/projects/active/maven/warbler/Rakefile:33:in `(root)'
org/jruby/RubyKernel.java:1073:in `load'
(See full trace by running task with --trace)

would it makes sense to somehow reduce those external dependencies ?

**Comment by jkutner** [comment]
Pretty sure this is not an issue any more.
