### ISSUE TITLE
"compiled" only compiles some

### ISSUE THREAD

**Issue by amiracam** [jruby/warbler#216]
weirdest thing, its only compiling certain .rb files but bypassing others, its almost like its not compiling anything that is required down the line from config.ru

What I want to do is create an executable war and or just war with compiled files.

all of my pertinent files are under lib, config.ru is at the top, don't have a bin

I am forcing the load path to my lib directory in case that has any bearing

**Comment by kares** [comment]
Warbler can not know the layout of any plain rack application (it does not load the app), there's standard FS layout for Rails and with gems it can resolve the files from gemspec but in general rack apps do not have any convention. thus one needs to tell Warbler what to compile.

**Comment by amiracam** [comment]
well thanks for the slightly late but appreciated response, do I assume you include Sinatra as a plain rack application ? thanks
