### ISSUE TITLE
load/run initializers as soon as War file deployed into Tomcat server.

### ISSUE THREAD

**Issue by mukeshsinghr** [jruby/warbler#228]
In my application we have __listener/consumer__ listening to __ActiveMQ__. Whose role is to take the data from __Queue__, Process data according to business logic and put the result(data) in database. Data is placed in __ActiveMQ__ by some other application. 

My job is to start the consumer as soon as __Tomcat__ server starts. How can I achieve this. 

I tried overloading method
<pre><code>public void contextInitialized(ServletContextEvent event) </code></pre> in class<pre><code>javax.servlet.ServletContextListener</pre></code> but no luck even though I am able overload method. Unable to start my consumer.

**Comment by kares** [comment]
... in this case you would really need to understand how jruby-rack boots and customize the web.xml
