### ISSUE TITLE
Unable to deploy on tomcat when move_jars_to_webinf_lib is true: Invalid gems-gems-warbler-1.4.2-spec-sample_war-some.jar

### ISSUE THREAD

**Issue by svrana** [jruby/warbler#256]
When using warbler 1.4.2 to create a war file for a sinatra app and specifying config.move_jars_to_webinf_lib = true in my config (or with the default config of warbler 1.4.1), Tomcat fails to start the webapp and I get this error message:

Mar 27, 2014 5:26:39 PM org.apache.catalina.startup.TldConfig tldScanJar
WARNING: Failed to process JAR [jar:file:/var/lib/tomcat7/webapps/auditlog/WEB-INF/lib/gems-gems-warbler-1.4.1-spec-sample_war-some.jar!/] for TLD files
java.util.zip.ZipException: zip file is empty

If I attempt to unzip the problematic jar I get this error message:

Archive:  gems-gems-warbler-1.4.1-spec-sample_war-some.jar
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of gems-gems-warbler-1.4.1-spec-sample_war-some.jar or
        gems-gems-warbler-1.4.1-spec-sample_war-some.jar.zip, and cannot find gems-gems-warbler-1.4.1-spec-sample_war-some.jar.ZIP, period.

The webapp works just fine if I use 1.4.2 and do not set config.move_jars_to_webinf_lib to true. Unfortunately I require this option to use jruby-rack-worker.

Any ideas?

**Comment by nasa42** [comment]
From https://github.com/ari/jobsworth/commit/626bf3992df388fdc864d43be74166c489d98e58
An workaround would be `config.move_jars_to_webinf_lib = /^((?!some\.jar).)*$/` (it excludes the invalid file which is named `some.jar`).

**Comment by kares** [comment]
fixed by #380 since we no longer include spec/integration parts of Warbler in the warbler .gem
