### ISSUE TITLE
Problems with posix spawn

### ISSUE THREAD

**Issue by SkyCrawl** [jruby/warbler#272]
Hello,

I tried to warble the gollum wiki and load it into Tomcat but the result .war file spawns the following http status 500 error when trying to access the wiki in browser:
<pre>
no such file to load -- posix_spawn_ext from org/jruby/RubyKernel.java:1065:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/posix-spawn-0.3.8/lib/posix/spawn.rb:2:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/posix-spawn-0.3.8/lib/posix-spawn.rb:1:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/posix-spawn-0.3.8/lib/posix-spawn.rb:1:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/gitlab-grit-2.6.9/lib/grit/git.rb:1:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/gitlab-grit-2.6.9/lib/grit/git.rb:2:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require' from file:/Users/Smolodon/Work/3rd party software/Webservers/apache-tomcat-7.0.30/webapps/PikaterWiki/WEB-INF/lib/jruby-stdlib-complete-1.7.13.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/gitlab-grit-2.6.9/lib/grit.rb:1:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/gitlab-grit-2.6.9/lib/grit.rb:34:in `(root)' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/gollum-lib-3.0.0/lib/gollum-lib.rb:1:in `(root)' from org/jruby/RubyBasicObject.java:1533:in `instance_eval' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/gollum-lib-3.0.0/lib/gollum-lib.rb:8:in `(root)' from /Users/Smolodon/.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/gollum-3.0.0/lib/gollum/app.rb:1:in `(root)'
</pre>

It doesn't seem to be formatted very well but the problem is stated right at the beginning. "posix_spawn_ext" is required in <code>../.rvm/gems/ruby-1.9.3-p547@swprojectdoc/gems/posix-spawn-0.3.8/lib/posix/spawn.rb:2</code> but can not be found. I tried to create a simple hello-world ruby with the same require and it works with my ruby-1.9.3-p547. Maybe the problem lies somewhere in jruby bundled in warbler? I didn't install jruby seperately...
As a side note:
1) The "posix-spawn" gem was not originally required I think. Even without it, I still got the same http status 500 error when trying to access the wiki in browser.
2) I found somewhere that <a href="https://github.com/headius/spoon">spoon</a> might be used as an alternative but it seems it would require some rewriting of the other gems and unfortunately I don't have that kind of skill just yet.

So, what's the catch here? Could there be a way around it or should I just try to move on to an alternative way to make gollum work in Tomcat? :)

For the sake of completeness, I'm running OS X.

**Comment by jkutner** [comment]
Closing this as we don't intend to support it on 1.x. Please try on 2.x with jruby 9k
