### ISSUE TITLE
jRuby profiling doesn't work if I packaged my app using warbler

### ISSUE THREAD

**Issue by thedebugger** [jruby/warbler#281]
When I package my app as a jar with warbler, I can't make profiling to work. I thought may be compiling java classes ahead-of-time might be the reason it is not working but it didn't work without it as well. Here is my setup –

command - bundle exec warble executable jar
jruby - 1.7.13
warbler - 1.4.4
config - https://gist.github.com/thedebugger/5b7633b11f4d2b12514f
JRUBY_OPTS="--profile.flat"

Bug may be? Or am I missing something?

**Comment by kares** [comment]
needs to be `-Djruby.runtime.arguments=--profile.flat` a semi-hack but known to be working.
