### ISSUE TITLE
Update the web.xml to Servlet 2.4 standard

### ISSUE THREAD

**Issue by tarraschk** [jruby/warbler#288]
Hi,

we wanted to deploy a WAR file made from warbler, on a server that uses LifeRay 6.2.

Unfortunately, it seems that Liferay 6.2 uses the Servlet 2.4 standard instead of 2.3.
As a result, we have to change the beginning of the web.xml.erb from
```
<!DOCTYPE web-app PUBLIC "-//Sun Microsystems, Inc.//DTD Web Application 2.4//EN" "http://java.sun.com/dtd/web-app_2_4.dtd">
<web-app>
```
to
```
<web-app
    xmlns="http://java.sun.com/xml/ns/j2ee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"
    version="2.4">
```
Some details: http://stackoverflow.com/questions/6816245/apache-tomcat-cannot-load-web-xml-connection-timed-out

We are working on that feature, but would you like us to push it on this repo?

Cheers

**Comment by jkutner** [comment]
This is done, we're at 3.1 now.
