### ISSUE TITLE
Symlink directory files not included in package

### ISSUE THREAD

**Issue by avinmathew** [jruby/warbler#292]
I recently tried upgrading to JRuby 1.7.16 from 1.7.9, but found that Warbler isn't packaging files within a symlinked directory. It will create a directory in the WAR representing the symlink, but there is no contents.

In my specific case, I'm using Capistrano to deploy a Rails application, and Capistrano uses a symlinked public/assets directory. Thus Warbler doesn't copy assets to the root of the WAR package.

I have tried each version from 1.7.9 to 1.7.16, and 1.7.9 is the last working version. I was hoping that the fixes in 1.7.15 and 1.7.16 around symlinks would fix the problem, but it doesn't seem to be so in my case.

I'm using Warbler 1.4.4.

**Comment by lukehorvat** [comment]
Yep. I am encountering the same thing in JRuby 1.7.21 / Warbler 1.4.8.

**Comment by jkutner** [comment]
Duplicated of #40
