### ISSUE TITLE
java files in gems don't get compiled with "gemjar"?

### ISSUE THREAD

**Issue by f0086** [jruby/warbler#293]
I've included the `eventmachine` gem among other gems. Warbler build the jar file with the features `gemjar` and `compiled`. After executing the jar file, the following error stops executing:

```
$ java -jar daemon.jar
LoadError: no such file to load -- rubyeventmachine
    require at org/jruby/RubyKernel.java:1065
     (root) at file:/.......daemon.jar!/gems/eventmachine-1.0.3/lib/jeventmachine.rb:31
```

[jeventmachine.rb](https://github.com/eventmachine/eventmachine/blob/master/lib/jeventmachine.rb) includes the line

```
require 'rubyeventmachine'
```

The file does not exist in the repository (as a ruby file), but as [a whole folder](https://github.com/eventmachine/eventmachine/tree/master/java/src/com/rubyeventmachine) with a bunch of java files in it. After creating the jar file, It holds the following files:

```
gems/eventmachine-1.0.3/ext/rubyeventmachine.so
[...]
gems/eventmachine-1.0.3/java/src/com/rubyeventmachine/
gems/eventmachine-1.0.3/java/src/com/rubyeventmachine/EmReactor.java
gems/eventmachine-1.0.3/java/src/com/rubyeventmachine/EmReactorException.java
gems/eventmachine-1.0.3/java/src/com/rubyeventmachine/EventableChannel.java
gems/eventmachine-1.0.3/java/src/com/rubyeventmachine/EventableDatagramChannel.java
gems/eventmachine-1.0.3/java/src/com/rubyeventmachine/EventableSocketChannel.java
```

It seems warble ignores these java files.

**Comment by kares** [comment]
closing due no feedback received.
