### ISSUE TITLE
Configuring database.yml for rails

### ISSUE THREAD

**Issue by btrepp** [jruby/warbler#298]
I'm a tad new to the java side of web applications (war files etc), but jruby+warbler+wildfly seems to result in a pleasant enough experience for running ruby apps on windows.

I'm confused how to customize the database.yml file after I have warbled my app though. 

My workflow would be like.
1) Warble rails application
2) distribute so multiple clients can consume it.

It seems I would have to tweak the database.yml and run warbler multiple times? That seems super weird. Would there be a way to 12 factor it with wildfly?.

What is the recommended way of configuring war files?.

**Comment by jkutner** [comment]
This is a very good question. Are you using Rails? If so, what version?

I've found that the `database.yml` pattern is problematic for many reasons. In particular, it doesn't work well with war files. To me, it's no better than putting database connection info in a `web.xml` or something. Putting config inside of a war file makes a portable artifact less portable.

I think a better way to specify database connection information is via environment variables. This is a tenet of [configuration in the 12 factor app](http://12factor.net/config). 

If you are using Rails 4.1 or newer, you can write your `database.yml` like so:

```yaml
production:
  url: <%= ENV['DATABASE_URL'] %>
```

Then you can set the `%DATABASE_URL%` env var depending on the customer/environment its running on. 

If you are using Rails < 4.1, I am not sure. But I suspect there is a way to use env vars. If you are not using Rails, I'm certain there's a way -- it just depends on what you're using (ActiveRecord, Sequel, etc).

**Comment by btrepp** [comment]
Yep I'm using rails :)

```
$ jruby -S bundle exec rails --version
Rails 4.1.8
```
I'd love to use a 12 factor methodology for it, but I got stumped about how I would document the configuration in wildfly.

http://stackoverflow.com/questions/24177314/jboss-setting-environment-variables-for-application

The best solution seemed to be modifying the startup scripts for the wildfly. This was obviously a little weird for me.

Atm I'm toying with the idea of actually having my warble/build process copy in a version of wildfly. At least then I am controlling the updates to wildfly (and the wildfly startup scripts), so I could possibly document how to change it.

**Comment by jkutner** [comment]
Oh i see. maybe it's possible then to use a system property instead of an env var? Like:

```yaml
production:
  url: <%= java.lang.System.getProperty("database.url") %>
```

Ideally, I think you would want to embed wildfly (i.e. include it as a dependency of your app and run it from code as opposed to deploying into it). This is definitely a goal of wildfly but I don't think it's possible yet. You should ask them about it :)

**Comment by btrepp** [comment]
I would even be happy with alternative containers that could support 12 factor style with ENV vars. Just thus far wildfly is the only one that worked out of tomcat, glassfish and wildfly :).

**Comment by jkutner** [comment]
Have you considered an executable war file? Or do you need to deploy into a container? The 12 factor style in Java is containerless.

**Comment by btrepp** [comment]
Executable war file would be perfect, I'm unsure how to run a war file as a service (in windows) though. It would be a great solution, I wouldn't need to depend on a container at all.

**Comment by jkutner** [comment]
[Java Service Wrapper](http://wrapper.tanukisoftware.com/doc/english/download.jsp) used to be the thing for that, but I have no idea about windows :P

Once you have an executable War (created by running `warble executable ...`), then you can run it with `java -jar myapp.war`. So maybe a simple windows service can be created with that command?
