### ISSUE TITLE
Deploying on heroku?

### ISSUE THREAD

**Issue by crysper** [jruby/warbler#314]
Has anyone successfully deployed the war file on heroku?

I can't get passed th heroku deploy:war --war <path>

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/heroku/sdk/deploy/DeployWar : Unsupported major.minor version 51.0

Heroku deploy supports JDK 1.8, I have installed(and running) JDK 1.8, can this be an error from the war file? I don't know Java stuff.

However, I feel that's not the only issues I will encounter, anyone here successfully deployed rails 4 app as war on heroku with postgres? I couldn't find anything online.

**Comment by jkutner** [comment]
Is the `java.lang.UnsupportedClassVersionError` happening during the local execution of the `heroku deploy:war` command? This usually indicates that you running code intended for JDK 8, on JDK 6. This would simply be an incompatibility between the deploy tool and your local JDK. The deploy tool requires JDK 7 or greater

As an alternative, you could deploy with the [heroku-maven-plugin](https://github.com/heroku/heroku-maven-plugin). Even if you `pom.xml` ends up just being a shell, like in [this example](https://github.com/jkutner/jruby-non-blocking-servlets-example).

**Comment by jkutner** [comment]
I should also note that once you get past the `java.lang.UnsupportedClassVersionError` error, you will most likely need to set the `WEBAPP_RUNNER_OPTS` config var with `--expand-war`.

**Comment by crysper** [comment]
Thanks for fast response.

I managed to solve the issue, it was Java version mismatch...and after a few hours I got it working on heroku. Yes, the WEBAPP_RUNNER_OPTS should be set on heroku environment variables.

**Comment by jkutner** [comment]
I made a sample app that demonstrates a few ways of doing this:
https://github.com/kissaten/warbler-example
