### ISSUE TITLE
LoadError with 'compiled' warble in 2.x with jruby9000

### ISSUE THREAD

**Issue by dwillie** [jruby/warbler#325]
When I warble my project with the compiled command I get the following error

`ERROR: org.jruby.exceptions.RaiseException: (LoadError) use 'java_import' to load normal Java classes: config.boot`

I'm using the 2.x warbler, and it works fine if I warble without the compiled flag. I need to use 2.x because I need JRuby9000 support.

It's worth noting that I also have found I need to unzip the war file, copy my config.ru from my project into the WEB-INF directory and then rezip it to have it work (otherwise I receive and error about its absence). I'm guessing I'm doing something wrong which is probably also causing this issue on compilation.

I have noticed I have to do the config.ru copy paste even with stable versions of warbler and earlier JRuby versions.

**Comment by jkutner** [comment]
This should be fixed with JRuby-9k.rc2. Please let us know if it's not.

**Comment by amiracam** [comment]
I am now bumping into this issue on jruby 9.2.00 , Warbler 2.0.5
