### ISSUE TITLE
Execute external ruby script using the war

### ISSUE THREAD

**Issue by dwillie** [jruby/warbler#330]
Is this at all possible? I'm looking to execute a ruby script that is on the target system, outside the .war file. The script is dependent on some of the gems within the .war file. The system has no version of ruby of it's own.

I've tried using `system(Gem.ruby, "path/to/file.rb")` to no effect and I've also tried using an approach more like `system("java -jar #{Rails.root.join("lib", "jruby-core-1.7.20.jar")} path/to/file.rb")`

The intent of the second approach was to use the temporary, unpacked jruby jar and seems to get closer but the script crashes as it can't find the gems it is dependent on that are bundled in the war file.

Thanks in advance, any help would be really appreciated.

Edit: 

`java -jar lib/jruby-core-1.7.20.jar -G Gemfile path/to/file.rb`

Seems to get me a step closer, and makes sense, but now I'm getting an error about the absence of rubygems. I've tried using `-cp lib` as well in an attempt to include the jruby-stdlib and jruby-rack jars with no success.

**Comment by mkristian** [comment]
you probably needs to set ```ENV['GEM_PATH']=Rails.root.join("gems")``` (hope I guess the usage of  the join method right) and you need to add all the jars from lib/ to your ```-cp```. jruby-core + jruby-stdlib is not enough since it misses all its dependencies.

**Comment by dwillie** [comment]
`GEM_PATH=gems BUNDLE_GEMFILE=Gemfile java -classpath "tmp/gems.jar;lib/*" -jar lib/jruby-core-1.7.20.jar -G ./Gemfile --debug ~/path/to/file.rb`

I've tried that and I still receive `LoadError: no such file to load -- rubygems`

My lib directory only contains `jruby-core-1.7.20.jar   jruby-rack-1.1.18.jar   jruby-stdlib-1.7.20.jar` as well as the tasks and assets directories, maybe something is missing from there?

Thanks a bunch for trying to help.

**Comment by mkristian** [comment]
OK this jruby-core is different from the jruby-core from maven-central - I
always miss this :)

let's try something slightly different:

GEM_PATH=gems BUNDLE_GEMFILE=Gemfile java -classpath
"tmp/gems.jar;lib/jruby-core-1.7.20.jar;lib/jruby-stdlib-1.7.20.jar"
org.jruby.Main --debug ~/path/to/file.rb

**Comment by dwillie** [comment]
You're my hero!

Thanks so much, that executed fine. Who knows how long it would've taken me to try that...

Thanks again!
