### ISSUE TITLE
Directories outside of Rails' conventions not recognized

### ISSUE THREAD

**Issue by lukehorvat** [jruby/warbler#335]
I have a Rails app with a `/public` directory containing various static files. Inside it, there is also a `/hello` subdirectory, which contains an `index.html` file.

When executing `warble compiled runnable war`, it seems warbler puts the `/hello` directory at the root of the WAR (i.e. the same level as `/WEB-INF`). Because of this, when I run the WAR via `java -jar app.war -S rails s`, the Rails app cannot find it.

If I un-zip the WAR, manually move the `/hello` directory to `/WEB-INF/public`, and then re-zip it, everything works properly. :frowning:

Am I doing something wrong here or does not warbler just not handle subdirectories within `/public` properly? Can I disable warbler's behaviour of placing `/public` files at the root of the WAR? I don't see what benefit it provides.

jruby 1.7.21 + warbler 1.4.8

**Comment by kares** [comment]
the "benefit" would be that Rails won't need to serve the public files. but if you depend on exact paths to the */public* files to work and read them it won't work. out of curiosity how are you expanding those paths? could you confirm that they're also not being served, if so under what servlet engine ?

**Comment by lukehorvat** [comment]
A bit hard to comment, since this was a while ago. But I am no longer storing the static files in `/public/hello`. Instead I've moved them to `/.hello` (in the root of the project) and serve them like so:

```ruby
hello_dir = File.expand_path('../../.hello', __FILE__)

Rails.application.routes.draw do
  mount Rack::Static.new(Rack::File.new(hello_dir), root: hello_dir, index: "index.html"), at: "/hello"
end
```

I'm still experiencing the same problem. Warbler doesn't include `/.hello` in the WAR file, so I have to manually copy it into `/WEB-INF`. It seems as though Warbler doesn't recognize any directories outside of Rails' conventions.

**Comment by kares** [comment]
right, well the original issue was interesting :) ... but .hello is a hidden file so its okay it's excluded.
to sum up the issue now is that with `config.includes += '.hello'` puts them the wrong place for you?

**Comment by lukehorvat** [comment]
Thanks! `config.includes = FileList[".hello/**/*"]` (i.e. with globbing) does the trick.
