### ISSUE TITLE
Rails::Server not defined

### ISSUE THREAD

**Issue by lukehorvat** [jruby/warbler#336]
I have a Rails 4.2 app with the following in one of the initializers:

```ruby
puts defined?(Rails::Server).nil?
```

When running it using JRuby 9.0.0.0, it prints out `false`, which is what I expect. But when running it as a WAR file (generated by the latest 2.x-dev version of Warbler), it prints out `true`. Any ideas what might be going on here?

**Comment by lukehorvat** [comment]
Just tested with JRuby 1.7.21 / Warbler 1.4.9 and it outputs `false` in both cases.

**Comment by jkutner** [comment]
Are you using the `compiled` feature?

**Comment by lukehorvat** [comment]
Yes... `warble compiled runnable war`

**Comment by lukehorvat** [comment]
Any update on this?

Tried again with JRuby 9.0.1.0 / Warbler 2.0.0.rc1 and get an error when running the WAR file:

```
ERROR: org.jruby.exceptions.RaiseException: (LoadError) /var/folders/p8/_7mz0qhd6wx5dfdsnl9yk6_40000gn/T/jruby3260062344812004372extract/config/boot.class is not compiled Ruby; use java_import to load normal classes
```

**Comment by jkutner** [comment]
@lukehorvat do you have an example app i can try this against real quick?

**Comment by lukehorvat** [comment]
https://github.com/lukehorvat/warbler-debug

It's just a blank Rails app + `config/initializers/hello.rb`.

**Comment by liuweijack** [comment]
I have the same problem with jruby-9.0.1.0 rails 4.2

**Comment by tandibar** [comment]
same error happening in our app, Rails 4.2, JRuby-9.0.3.0, warbler 2.0.0.rc1:

    ERROR: initialization failed: org.jruby.rack.RackInitializationException: [...]/config/boot.class is not compiled Ruby; use java_import to load normal classes
        from org/jruby/RubyKernel.java:957:in `load'
        from [...]/config/boot.rb:1:in `<top>'
        from org/jruby/RubyKernel.java:939:in `require'
        from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)'
        from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from uri:classloader:/jruby/rack/rails/environment3.rb:23:in `load_environment'
        from uri:classloader:/jruby/rack/rails_booter.rb:83:in `<top>'

**Comment by reinvanmeeteren** [comment]
We have the same problem in our app (not using rails): Jruby-9.0.3.0, warbler 2.0.0.rc1

**Comment by tandibar** [comment]
Perhaps the title should be changed because i think it has nothing to do with Rails::Server. It's just the `compiled` feature which breaks the code. We have deaktivated the `compiled` feature for now and everything works fine.

**Comment by abiacco** [comment]
Another "me too" for the "not compiled" error.
jruby 9.0.3.0/9.0.4.0, warbler 2.0.0.rc1, java 1.8.0_60.
This is the first time i've tried to compile ruby files, namely in app/ and config/

**Comment by kares** [comment]
bug in JRuby 9K - there's actually several, most recent which was still present in 9.0.5.0 : https://github.com/jruby/jruby/issues/3651
