### ISSUE TITLE
no such file to load -- META-INF/init with warbler 2.0.0.pre2

### ISSUE THREAD

**Issue by sdesbure** [jruby/warbler#337]
Hello, I used to build my war using warbler 1.4.9 anf jruby 1.7.21.
I wanted to try jruby 9.0.0.0 so I installed warbler 2.0.0.pre2.

I did as usual and I have the following error:

```bash
bundle exec warble runnable war
java -jar OrchestratorGui.war -S rake -T
LoadError: no such file to load -- META-INF/init
  require at org/jruby/RubyKernel.java:940
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
    <top> at <script>:3
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- META-INF/init
```

I looked into the WAR and I have an init.rb file in META-INF...
any clues?

versions infos:

```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 OpenJDK 64-Bit Server VM 24.79-b02 on 1.7.0_79-b14 +jit [linux-amd64]
Bundler version 1.10.6
Warbler 2.0.0.pre2
```

**Comment by jkutner** [comment]
I've fixed this here:
https://github.com/jruby/warbler/commit/f1d8f23732282bede392a4b4bde63eec23a19979

But i guess it's not released (I thought it was). I'll cut a pre3 ASAP.

**Comment by jkutner** [comment]
Please check out [2.0.0.pre3](https://rubygems.org/gems/warbler/versions/2.0.0.pre3) and let me know if it works.
