### ISSUE TITLE
Warbler + winstone and Sinatra's set :public truncating big files?

### ISSUE THREAD

**Issue by napcs** [jruby/warbler#34]
I'm setting the public directory in lib/server.rb to an absolute path. If I place jquery.min.js in it and serve it, the file gets truncated.

Under JRuby with 

    rackup config.ru

everything works great. There's no truncation at all.

But with

   jruby -S warble executable war

and then running with java -jar warname.war

when I visit http://localhost:8080/jquery.min.js, It truncates for me with safari, ff, chrome, and curl. I'm extremely lost.

Here's a  simple app that isolates the problem:

https://gist.github.com/1018160

Any help would be greatly appreciated. 

*edit* I'm on a Mac, with Snow Leopard.
Java version:

Java(TM) SE Runtime Environment (build 1.6.0_24-b07-334-10M3326)
Java HotSpot(TM) 64-Bit Server VM (build 19.1-b02-334, mixed mode)

Tried with JRuby 1.6.2 and 1.6.1. With warbler 1.3.0 and 1.3.1. And various combinations of Sinatra, rack, jruby-rack versions too.

**Comment by kares** [comment]
jetty is the default now thus issue no longer relevant ... let us know otherwise, thx!
