### ISSUE TITLE
PORT environment variable has no effect on runnable war in windows

### ISSUE THREAD

**Issue by jcsjcs** [jruby/warbler#342]
This works in a linux script (jetty runs on port 80):
```shell
export PORT=80
java -Xmx1536m -Xms1536m -jar jmt_cms.war
```
But in a windows batch file this does not work (jetty runs on port 8080):
```batch
SET PORT=80
java -Xmx1536m -Xms1536m -jar jmt_cms.war
```
The war file was built with warbler 1.4.9.

**Comment by jkutner** [comment]
I wasn't able to reproduce this. Can you provide some more details about the environment? Can you also check that PORT was set correct by running `echo %PORT%`?

If you need a workaround, add `-Dwarbler.port=80` to your `java` command.

**Comment by jcsjcs** [comment]
I see now that the environment variable in my test script was in lower case, so it wasn't taking.
Using `PORT` instead of `port` works fine. Sorry for wasting your time.
