### ISSUE TITLE
How to bind to static IP?

### ISSUE THREAD

**Issue by tidelake** [jruby/warbler#343]
I've run `warble config` and looked through the file, but I don't see how to bind the embedded jetty server to a static IP. I'm sure this isn't an issue, but I'd appreciate your help.

I'm using `warble compiled executable war` and `java -jar app.war`

**Comment by jkutner** [comment]
Currently, I think this may only be possible by providing a custom Jetty configuration. But we should have a `warbler.host` option like the `warbler.port` option: https://github.com/jruby/warbler/blob/master/ext/WarMain.java#L143

**Comment by tidelake** [comment]
Is there a resource on how to configure the embedded Jetty server?

**Comment by jkutner** [comment]
It uses jetty-runner, so this is the doc: http://www.eclipse.org/jetty/documentation/current/runner.html

But you'd have to define a customer config using webserver.properties file: https://github.com/jruby/warbler/blob/master/ext/WarMain.java#L33

It's all a little convoluted right now.

**Comment by tidelake** [comment]
Thank you. I'll hope for the `warbler.host` option soon!

**Comment by jkutner** [comment]
@tidelake i pushed 2.0.0.rc1 (if you're using jruby-9k). I'll have 1.4.10 out later. might be tomorrow.
