### ISSUE TITLE
RVM interfering with Warbler (2.0.0.rc1)

### ISSUE THREAD

**Issue by mamantoha** [jruby/warbler#344]
The behaviour of the jar differs depending on which Ruby version RVM is using: if I rvm use JRuby (9.0.1.0) then the jar works normally, but if I rvm use 2.2.3 then running the jar prints these warning messages to the console:

```
$ java -jar app.jar
Ignoring unf_ext-0.0.7.1 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.1
```

Warnings are prints even when I set `override_gem_home` in the warble config to `false`.

**Comment by jkutner** [comment]
I was able to reproduce this. I think it may have something to do with a change in Bundler or RVM. Can you tell me what version of each you are using? `bundler version` and `rvm -v`

**Comment by mamantoha** [comment]
```
$ bundle version
Bundler version 1.10.6
```

```
$ rvm -v
rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

**Comment by dometto** [comment]
:+1:

In fact when I run the `.war` I've generated with warbler, it seems to insist on using the gem dependencies from my `~/.rvm/gems` directory -- *not* the gems packaged in the `.war` archive. So it seems like warbler does not generate self-contained archives?

**Comment by jkutner** [comment]
@dometto no, warbler doesn't generate self-contained archives and this whole project is just a big troll. this is a bug with 2.x. Something with rvm, bundler, or jruby 9k has changed and is causing it. use 1.4.x until it's fixed if you need warbler.

**Comment by dometto** [comment]
Thanks for the quick reply, @jkutner. Didn't mean to suggest the project is a troll at all -- was just in a hurry and I tried to find a way to describe the elusive problem I was experiencing. Sorry if I sounded rude.

I'm not using 9k, so that's probably not the cause. I'll experiment with different versions of rvm and bundler and let you know. Are there any significant drawbacks to using 1.4.x compared to 2.x?

**Comment by jkutner** [comment]
@domette sorry, i shouldn't be such a dick. The only difference between 2.x and 1.4.x is 9k support. So 1.4.x should be fine. 

Also, i think this maybe an RVM or Bundlet thing. So if you hit it with 1.4.x please let us know, and maybe try an earlier version of those.

**Comment by mamantoha** [comment]
I found the solution. Unset `GEM_HOME` and `GEM_PATH` environment variables.

`GEM_PATH="" GEM_HOME="" java -jar name.jar`

I think this should work as default behaviour. Can someone look at this?
