### ISSUE TITLE
Executable War doesn't start from 1.4.9

### ISSUE THREAD

**Issue by pierrickrouxel** [jruby/warbler#346]
I use warbler to build an executable War. In 1.4.8 all works correctly.
When I upgrade to 1.4.9, my server fails to start. I have the error:

```
Invalid class pointer in stack allocated object in thread org.eclipse.jetty.server.session.HashSessionManager
```

And then java requires a memory purge.

Can you help me?

**Comment by jkutner** [comment]
Are you building an executable war?

**Comment by pierrickrouxel** [comment]
Yes I say it previously.

In my warble.rb
```ruby
config.features = %w(executable)
config.webserver = 'jetty'
```

**Comment by pierrickrouxel** [comment]
Sorry it's not a bug with warbler but with IBM JDK 7.1/8.0. I don't know why but they seems to crash with jetty on my machine.
