### ISSUE TITLE
Warbler produced JAR use external Java class files instead of internal ones

### ISSUE THREAD

**Issue by cwchentw** [jruby/warbler#350]
```
$ cd oneProject
$ cat bin/app
require 'java'
$CLASSPATH << "target/classes"
java_import 'com.example.Greeting'

greeting = Greeting.new
puts greeting.hello

$ cat target/classes/com/example/Greeting.java
package com.example;

public class Greeting {
    public String hello() {
	return "Hello";
    }
}
```

The JAR produced by Warbler will become unusable if the directory target renamed or the JAR file moved.  Any solution?

**Comment by jkutner** [comment]
Include the class files in the WAR with a [config.includes](https://github.com/jruby/warbler/blob/master/warble.rb#L17). You could even put them in a dir that's already on the path.
