### ISSUE TITLE
Missing version.rb file in the included ActiveSupport gem.

### ISSUE THREAD

**Issue by niuage** [jruby/warbler#351]
Hey,

I created a jar of my little app with warble, just running `warble` (on mac). I use Bundler. The jar was created without any issues. When I try to run it on windows though, I get this error:

![](http://i.imgur.com/mNOO0hc.png)

I opened the jar with netbeans to see what was in it exactly, and all the gems seem to be included, but I dont see the version.rb file for the active support gem though.

Any help would be appreciated! Thanks :+1:

**Comment by niuage** [comment]
I think the bug just comes from the fact that, for some reason, the jar still takes the context into account. Because it works on mac, in the folder I created the jar. As soon as I change the jar location though, even on mac, I get other errors about missing files and failed requires.

**Comment by kares** [comment]
try un-setting `GEM_HOME` and `GEM_PATH` ... as you mentioned it depends on which folder you're at
maybe even check for BUNDLE_ variables
