### ISSUE TITLE
Maven jruby integration using pom.xml

### ISSUE THREAD

**Issue by omgithub19** [jruby/warbler#352]
I  am trying to maven jruby integration, running build by pom.xml  using command mvn package .
getting below error.
 Failed to collect dependencies at rubygems:guard:'gem:2.13.0 -> rubygems:listen:'gem:2.7.6 -> rubygems:celluloid:'gem:0.17.0 -> rubygems:celluloid-essentials:'gem:0.20.0.pre12-SNAPSHOT -> rubygems:celluloid-gems:'gem:[0,): No versions available for rubygems:celluloid-gems:'gem:[0,) within specified range -> [Help 1]

versions: 
Warbler 1.4.9
Jruby 1.7.3
JDK 1.6
Maven 3.2.5

**Comment by mkristian** [comment]
looking at rubygems:celluloid-essentials:gem:0.20.0.pre12-SNAPSHOT it has a
dependency which is not on rubygems.org and also not on the maven-proxy of
rubygems.org and fails. actually it was yanked:
https://rubygems.org/gems/celluloid-gems

this means you need to add an extra constraints to resolve it, most
celluloid gem just use open version ranges and whenever there is a single
"bad" in it things fail on the maven side. have not seen such gem
resolution problems for a very long time.

workaround:

gem 'guard', '2.13.0', :exclusions => ['rubygems:listen']
gem 'listen', '[3.0.0,4.0.0)'

**Comment by omgithub19** [comment]
thanks a lot @mkristian

**Comment by omgithub19** [comment]
My Jruby war file is generated by using warbler, maven and pom.xml but while I deploying on web logic, it is giving below error .

 Failure occurred in the execution of deployment request with ID '1446451837145' for task '11'. Error is: 'weblogic.application.ModuleException: ' weblogic.application.ModuleException: at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1520) at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:484) at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:425) at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52) at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:119) at weblogic.application.internal.flow.ScopedModuleDriver.start(ScopedModuleDriver.java:200) at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:247) at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:425) at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52) at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:119) at weblogic.application.internal.flow.StartModulesFlow.activate(StartModulesFlow.java:27) at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:671) at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52) at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:212) at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:44) at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:161) at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:79) at weblogic.deploy.internal.targetserver.operations.AbstractOperation.activate(AbstractOperation.java:569) at weblogic.deploy.internal.targetserver.operations.ActivateOperation.activateDeployment(ActivateOperation.java:150) at weblogic.deploy.internal.targetserver.operations.ActivateOperation.doCommit(ActivateOperation.java:116) at weblogic.deploy.internal.targetserver.operations.StartOperation.doCommit(StartOperation.java:149) at weblogic.deploy.internal.targetserver.operations.AbstractOperation.commit(AbstractOperation.java:323) at weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploymentCommit(DeploymentManager.java:844) at weblogic.deploy.internal.targetserver.DeploymentManager.activateDeploymentList(DeploymentManager.java:1253) at weblogic.deploy.internal.targetserver.DeploymentManager.handleCommit(DeploymentManager.java:440) at weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.commit(DeploymentServiceDispatcher.java:163) at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.doCommitCallback(DeploymentReceiverCallbackDeliverer.java:195) at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.access$100(DeploymentReceiverCallbackDeliverer.java:13) at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer$2.run(DeploymentReceiverCallbackDeliverer.java:68) at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:545) at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256) at weblogic.work.ExecuteThread.run(ExecuteThread.java:221) Caused By: java.lang.UnsupportedClassVersionError: org/jruby/runtime/builtin/IRubyObject : Unsupported major.minor version 51.0 at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631) at java.lang.ClassLoader.defineClass(ClassLoader.java:615) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:343) at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:302) at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:270) at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:64) at java.lang.ClassLoader.loadClass(ClassLoader.java:306) at java.lang.ClassLoader.loadClass(ClassLoader.java:247) at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:179) at weblogic.utils.classloaders.ChangeAwareClassLoader.loadClass(ChangeAwareClassLoader.java:43) at org.jruby.rack.rails.RailsServletContextListener.newApplicationFactory(RailsServletContextListener.java:25) at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:45) at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:481) at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321) at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120) at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:181) at weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAppServletContext.java:1868) at weblogic.servlet.internal.WebAppServletContext.start(WebAppServletContext.java:3154) at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1518) at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:484) at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:425) at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52) at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:119) at weblogic.application.internal.flow.ScopedModuleDriver.start(ScopedModuleDriver.java:200) at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:247) at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:425) at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52) at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:119) at weblogic.application.internal.flow.StartModulesFlow.activate(StartModulesFlow.java:27) at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:671) at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52) at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:212) at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:44) at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:161) at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:79) at weblogic.deploy.internal.targetserver.operations.AbstractOperation.activate(AbstractOperation.java:569) at weblogic.deploy.internal.targetserver.operations.ActivateOperation.activateDeployment(ActivateOperation.java:150) at weblogic.deploy.internal.targetserver.operations.ActivateOperation.doCommit(ActivateOperation.java:116) at weblogic.deploy.internal.targetserver.operations.StartOperation.doCommit(StartOperation.java:149) at weblogic.deploy.internal.targetserver.operations.AbstractOperation.commit(AbstractOperation.java:323) at weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploymentCommit(DeploymentManager.java:844) at weblogic.deploy.internal.targetserver.DeploymentManager.activateDeploymentList(DeploymentManager.java:1253) at weblogic.deploy.internal.targetserver.DeploymentManager.handleCommit(DeploymentManager.java:440) at weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.commit(DeploymentServiceDispatcher.java:163) at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.doCommitCallback(DeploymentReceiverCallbackDeliverer.java:195) at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.access$100(DeploymentReceiverCallbackDeliverer.java:13) at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer$2.run(DeploymentReceiverCallbackDeliverer.java:68) at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:545) at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256) at

 Please help me out.

**Comment by mkristian** [comment]
it is jdk version problem you are running jdk6 and there error says there are jdk7 class files. which jruby version do you use ?

**Comment by omgithub19** [comment]
Initially I was using jdk 7 after that I installed jdk 6 also ( without uninstalled jdk7) only change in class path.
my Jruby  version 1.7.3

**Comment by omgithub19** [comment]
I have uninstalled JDK7 still giving the same error while I am deploying on Web logic.  
"Caused By: java.lang.UnsupportedClassVersionError: org/jruby/runtime/builtin/IRubyObject : Unsupported major.minor version 51.0 at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)"

my version details:
$ jruby --version
jruby 1.7.13 (1.9.3p392) 2014-06-24 43f133c on Java HotSpot(TM) 64-Bit Server VM 1.6.0_45-b06 [Windows 7-amd64]

**Comment by mkristian** [comment]
I am not sure if the commandline version of jruby is the same as the one you pack into the war-file. just look into the warfile under WEB-INF/lib and maybe here you can see the jruby version. also jruby-rack produces some nice dump on startup errors including the jruby version.

you error says: you can not use jdk6
and jdk7 comes with major.minor version 51.0 which can not give this error ! so uninstall jdk6 and install jdk7 is one way to go

**Comment by omgithub19** [comment]
Now I uninstalled everything and install again .. now i am getting below error


[WARNING] warble aborted!
[WARNING] LoadError: no such file to load -- rakefile
[WARNING] C:/working/csw-cssm-engine/lic_engine_app/target/gems/gems/warbler-1.3.8/lib/warbler/application.rb:61:in `load_project_rakefile'
[WARNING] C:/working/csw-cssm-engine/lic_engine_app/target/gems/gems/warbler-1.3.8/lib/warbler/application.rb:59:in `load_project_rakefile'
[WARNING] C:/working/csw-cssm-engine/lic_engine_app/target/gems/gems/warbler-1.3.8/lib/warbler.rb:26:in `project_application'
[WARNING] C:/working/csw-cssm-engine/lic_engine_app/target/gems/gems/warbler-1.3.8/lib/warbler/traits/rails.rb:27:in `before_configure'

version:
JDK 6
Jruby 1.7.13
rake (10.1.0)
warbler (1.3.8)

**Comment by mkristian** [comment]
@omgithub19 we are getting somewhere. could you share the pom.xml you are using the generate the warfile with warbler ? looks like it does not pack the Rakefile into the war. maybe just a misconfigured config/warble.rb

**Comment by omgithub19** [comment]
as i read somewhere that upgrade the warbler version so I upgraded to 1.4.9
Now it has been successfully generated war file and also uploaded to web logic.

thanks of the help,

**Comment by mkristian** [comment]
welcome
