### ISSUE TITLE
Installing jetty-runner fails on windows

### ISSUE THREAD

**Issue by marjaimate** [jruby/warbler#355]
Jruby version: 9.0.4.0
Warbler version: 2.0.0rc2
OS: Windows 7

Installing the gem went fine, but when trying to create the war file with `warble executable war` it fails with an error, that seems to suggest that windows & unix path is mangled up:

```
Errno::ENOENT No such file or directory - \\Path\To\Folder/.m2/repository/org/eclipse/jetty/jetty-runner/9.2.9.v20150224/jett-runner-9.2.9.v20150224.jar
C:\jruby-9.0.4.0\bin\warble:23:in '<top>'
Tasks: TOP => war:files
```

**Comment by jkutner** [comment]
What was the `\\Path\To\Folder` value? Was it your `HOME` directory? Does the `.m2` dir exist there?

**Comment by marjaimate** [comment]
@jkutner yes, it was my `HOME`, something like `\\Users\mate`

**Comment by kares** [comment]
seems like a bug with FS path handling (under Windows) in JRuby 9.0.4, updating JRuby should solve ...
