### ISSUE TITLE
Intermittent Tomcat7 load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERBoolean

### ISSUE THREAD

**Issue by fun-ruby** [jruby/warbler#356]
Seasons Greetings!

Apologies for lengthy post but I haven't been able to find issues reported similar to ours.

For some time now we have been experiencing this error on Tomcat7 start up or restart with deployed warbler war files. When all wars load successfully everything works perfectly. The error isn't consistent as it only happens about 25%-35% of the time, with repeated tomcat restarts.

We have multiple war files deployed on the same tomcat instance on a full deployment. Usually only one random war file fails to load, others load fine. The same is observed even with just one deployed war.

We are using:
* warbler 1.4.5
* jruby 1.7.19
* rails 4.1.9
* SLES 11/12 with 4GB, 1 or 2 CPU cores - see more load errors with 2 cores than 1!
* Sun jdk1.7.0_76/jre
* tomcat 7.0.59

```
# tomcat/bin/setenv.sh
JAVA_OPTS="-server -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xms64m -Xmx2048m -XX:PermSize=64m -XX:MaxPermSize=768m"
```

Below are sections extracted from the full back trace.

```
INFO: An exception happened during JRuby-Rack startup
load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERBoolean
--- System
jruby 1.7.19 (2.0.0p598) 2015-01-30 32f5af0 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_76-b13 +jit [linux-amd64]
Server: Apache Tomcat/7.0.59
jruby.home: file:/srv/tomcat7/webapps/foo/WEB-INF/lib/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home

--- Context Init Parameters:
jruby.compat.version = 2.0
jruby.max.runtimes = 4
jruby.min.runtimes = 2
public.root = /
rails.env = production

--- Backtrace
LoadError: load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERBoolean
  require at org/jruby/RubyKernel.java:1071
   (root) at /srv/tomcat7/webapps/foo/WEB-INF/lib/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1
  require at org/jruby/RubyKernel.java:1071
   (root) at /srv/tomcat7/webapps/foo/WEB-INF/gems/gems/activesupport-4.1.9/lib/active_support/key_generator.rb:1
...
  require at org/jruby/RubyKernel.java:1071
   (root) at /srv/tomcat7/webapps/foo/WEB-INF/gems/gems/railties-4.1.9/lib/rails/all.rb:1
   (root) at /srv/tomcat7/webapps/foo/WEB-INF/gems/gems/railties-4.1.9/lib/rails/all.rb:1
   (root) at /srv/tomcat7/webapps/foo/WEB-INF/config/application.rb:1
...
```

```
...
SEVERE: ERROR: unable to initialize application
org.jruby.exceptions.RaiseException: (LoadError) load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERBoolean
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
	at RUBY.(root)(/srv/tomcat7/webapps/foo/WEB-INF/lib/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
	at RUBY.(root)(/srv/tomcat7/webapps/foo/WEB-INF/gems/gems/activesupport-4.1.9/lib/active_support/key_generator.rb:1)
...
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERBoolean
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
	at RUBY.(root)(/srv/tomcat7/webapps/foo/WEB-INF/lib/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl/load.rb:19)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
	at RUBY.(root)(/srv/tomcat7/webapps/foo/WEB-INF/lib/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1)
...
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.DERBoolean
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.jruby.util.JRubyClassLoader.findClass(JRubyClassLoader.java:183)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.jruby.ext.openssl.ASN1.<clinit>(ASN1.java:453)
	at org.jruby.ext.openssl.OpenSSLReal.createOpenSSL(OpenSSLReal.java:138)
	at org.jruby.ext.openssl.OSSLLibrary.load(OSSLLibrary.java:10)
...
```

**Comment by mkristian** [comment]
from a first look at your info there are two questions:
* are there bouncy-castle jars somewhere on tomcat or extension classloader other the ones coming from jruby
* does the error disappear when using only a single runtime instead of min 2 and max 4 ?

**Comment by fun-ruby** [comment]
@mkristian,

* we only use standard tomcat install and warbler war files, so no other bouncy-castle jars on the path
* actually I was just testing a single war with min runtime 1. Early results are promising since no load errors insofar. I will report back with further results in a few days.

**Comment by fun-ruby** [comment]
@mkristian, its been more than a few days ... sorry.

Good news is I can confirm the problem went away when setting `config.webxml.jruby.min.runtimes = 1`. I've restarted tomcat for a good part of a day without being able to reproduce the issue. Tomcat startup is also up faster too, taking about half the previous time (when min.runtimes=2). This makes sense since additional runtimes do take additional time and RAM.

The bad news is our QA is reporting benchmark degradation. We have some long-running operations that are now taking twice as long to complete. This sorta make sense since we only start with the one runtime. However, I do have max runtime set at 3 (was 4 previously). I had assumed the number of run times would grow as required. This doesn't seem to be the case. Do you know under what condition(s) the pool would grow to max?

**Comment by kares** [comment]
heh - haven't seen a non-thread-safe jruby-rack setup in a while :) ... the pool should grow on demand (if a request comes in and there's no runtime available) - that is likely the cause of the slow-down. however, on production instances its usually a good idea to pre-boot "more" runtimes (as you had 2). 

would consider the option of moving the BC jars up the CP and setting JRuby-OpenSSL [not to load the .war bundled ones](https://github.com/jruby/jruby-openssl/blob/master/lib/jopenssl/load.rb#L7) or setting `config.move_jars_to_webinf_lib = /^(bcp|jruby)/`

**Comment by mkristian** [comment]
@kares having classloader problems with several runtimes with ScriptingContainer (jruby-rack uses it for its pool) is a known issue: https://github.com/jruby/jruby/issues/2561 - never found the time to fix it. will prepare are PR now. not absolutely sure if this issue and my jruby issues is absolutely the same but they look like.

see also this conversion here : http://ruby.11.x6.nabble.com/JRuby-complete-multi-threading-and-java-lang-NoClassDefFoundError-td5004808.html

**Comment by mkristian** [comment]
@fun-ruby any chance to use jruby-9.0.4.0 instead of jruby-1.7.19 ? the issues is most likely gone there.

**Comment by fun-ruby** [comment]
@kares non-thread-safe can be a beast. It should be tamed but not feared :)

Decided to try `config.move_jars_to_webinf_lib = true` with pre-boot runtimes at 2:4. WEB-INF/lib/ has the following jars:

```
gems-gems-activerecord-jdbc-adapter-1.3.14-lib-arjdbc-jdbc-adapter_java.jar
gems-gems-jdbc-jtds-1.3.1-lib-jtds-1.3.1.jar
gems-gems-json-1.8.2-java-lib-json-ext-generator.jar
gems-gems-json-1.8.2-java-lib-json-ext-parser.jar
gems-gems-thread_safe-0.3.4-java-lib-thread_safe-jruby_cache_backend.jar
jruby-core-1.7.19.jar
jruby-rack-1.1.18.jar
jruby-stdlib-1.7.19.jar
```

The `gems*.jar` files are new but I don't see any BC jar.

On the third tomcat restart I got the error again :(

**Comment by fun-ruby** [comment]
@mkristian we are near the end of QA cycle so it isn't possible for this release. Will consider jruby-9.x for a future release.

**Comment by kares** [comment]
@fun-ruby maybe its not part of your `Gemfile` ... also worth trying would be updating jruby-openssl gem

**Comment by mkristian** [comment]
@fun-ruby just add ```jruby-openssl``` with different version then the one coming with jruby-1.7.19, i.e. the latest will do.

**Comment by fun-ruby** [comment]
@kares @mkristian that was the missing piece! Added jruby-openssl 0.9.13 to Gemfile and the BC jars are now in WEB-INF/lib.

So far so good since we don't see the error anymore. Plus tomcat seems to deploy WAR faster with jars being found earlier on the CP.

Thank you both for helping with this.
Cheers!
