### ISSUE TITLE
Missing Gem Dependency

### ISSUE THREAD

**Issue by jamesward** [jruby/warbler#36]
When I try to gem install warbler I get the following error:
ERROR:  While generating documentation for warbler-1.3.1
... MESSAGE:   exit
... RDOC args: --ri --op /usr/lib/ruby/gems/1.8/doc/warbler-1.3.1/ri --main README.txt -SHN -f darkfish lib History.txt LICENSE.txt Manifest.txt README.txt --title warbler-1.3.1 Documentation --quiet

If I run the rdoc command I get:
rdoc --ri --op /usr/lib/ruby/gems/1.8/doc/warbler-1.3.1/ri --main README.txt -SHN -f darkfish lib History.txt LICENSE.txt Manifest.txt README.txt --title warbler-1.3.1 Documentation --quiet

Invalid output formatter

For help on options, try 'rdoc --help'

Then I did:
sudo gem install darkfish-rdoc

Then I could install the warbler gem.

**Comment by kares** [comment]
old issue - no longer relevant ... let us know otherwise, thx!
