### ISSUE TITLE
Any plans to support JRuby 9000

### ISSUE THREAD

**Issue by zhao-li** [jruby/warbler#360]
Hi,

I was wondering if there's any plans to support JRuby 9000:
https://github.com/jruby/warbler/blob/master/warbler.gemspec#L26-L27

Thanks!

**Comment by jkutner** [comment]
Version [2.0.0.rc2](https://rubygems.org/gems/warbler/versions/2.0.0.rc2) supports JRuby 9k

**Comment by zhao-li** [comment]
Thanks!
![Awesome!](https://media.giphy.com/media/VerIk7pS3iEEg/giphy.gif)
