### ISSUE TITLE
project relying on gem with native extensions

### ISSUE THREAD

**Issue by mooreniemi** [jruby/warbler#372]
I'm likely Doing Things Wrong here, so this is more an ask for help than a report that something is wrong.

I have a gem that uses [lock_jar](https://github.com/mguymon/lock_jar) to manage the native java extensions, but I am also requiring a jar the gem itself manages. The gem's jar is a patch, basically, on the native extensions it depends on.

So I have one entry in the gem's `Jarfile`, and the generated `Jarfile.lock` has all the transitive dependencies. I want to use this gem in a jruby project, and I ultimately want to use warbler to turn that project into a jar.

When I create the jar of the project though, it appears to have access to the native extensions (I see in the logs it is running one of those classes), but then: `LoadError: load error: META-INF/main -- javassist.CannotCompileException: by java.lang.NoClassDefFoundError: one/of/my/Classes`, where the missing class definition is the jar that patches the native extension dependencies. (This is mysterious to me, because I know those classes are available when I `.get` them from the `ClassPool`.)

If I just run with `jruby` rather than in a jar, it works fine. The only way I can get it to find the native extension classes in that context is to specify `# config.java_libs += FileList["/Users/me/.m2/repository/example/example.jar"]` in `config/warble.rb`. Meaning I effectively have to duplicate the dependency information of the gem in the project that depends on that gem.

That seems wrong to me, so I figure I am goofing this up.

For clarity, the elements again are: an sdk I don't have control over in a jar I manage via Jarfile, a jar I _do_ have control over in the gem that depends on classes from the sdk that is just included in the gem, and finally a project that has the gem listed in its Gemfile that I want to warble.

**Comment by mkristian** [comment]
for the time being you need to use jbundler to manage your jar-dependencies with warbler. and I am working on integrating jar-dependencies as this comes pre-installed with jruby which exeeds/replaces the jbundler stuff.

the lock_jar is not supported by warbler.

**Comment by mooreniemi** [comment]
@mkristian i will give that a shot. i edited my post though as i'd missed something. my situation is a bit more complex than "lock_jar doesnt work with warbler". in fact it seems lock_jar _does_ work with warbler. but somehow now from javassist's perspective.

**Comment by mkristian** [comment]
@mooreniemi jbundler depends on jar-dependencies declarations inside the gemspec of the gem: 

https://github.com/mkristian/jar-dependencies/blob/master/example/example.gemspec#L28

that is also how all the bundled gems with jars declare the jar-dependencies, so jbundler will deal with all those internal gems as well your gems, to resolve the transitive dependencies. 

I do not know about javassist - maybe something tries to compile java files you bundle with your gem ? which I saw before.

**Comment by mooreniemi** [comment]
@mkristian hmm, i thought given the documentation on jbundler i was ok using a Jarfile, but Jarfile doesn't take the place of jar-dependencies declarations inside the gemspec?

i think i'm definitely not understanding the behavior of the various loaders. what confuses me is that i know my program in general has access to the classes javassist claims it cant load.

**Comment by mooreniemi** [comment]
also I tried following https://github.com/mkristian/jar-dependencies#vendoring-your-jars-before-packing-the-jar and it didn't create the the _jars.rb file in lib, but instead created `Users/amooreniemi/.rvm/gems/jruby-9.0.5.0/extensions/universal-java-1.8/2.2.0/workerbee-0.4.9/workerbee_jars.rb`

**Comment by mooreniemi** [comment]
another issue that is confusing me, if i do `config.java_libs += FileList["vendor/bundle/jruby/2.2.0/gems/workerbee-0.4.8/vendor/jars//zipcar/cheetah-sdk/1.8.1/cheetah-sdk-1.8.1.jar"]` my javassist error shifts to the next transitive dependency. but if i include all my vendor/jars jars in the `FileList` then it goes right back to erroring as if my sdk wasn't in the list. :/

**Comment by mooreniemi** [comment]
I figured out my problem -- when running as a jar, the classloader I was expecting to be default was not. Totally just my misunderstanding. I'm sorry to have wasted your time on here.
