### ISSUE TITLE
"ignoring x because its extensions are not built"

### ISSUE THREAD

**Issue by mooreniemi** [jruby/warbler#374]
I'm on a very minimal Alpine Linux box with java 1.8 and jruby 9.0.5.0 (no `rvm` or `rbenv`). My program includes a Gemfile, and one of the gems in the Gemfile has jar extensions. Everywhere I look, it appears the extensions are built correctly. (`gem env` gives 2 results aside from my `vendor/bundle` and there's an entry for this gem in the `extensions` dir as I'd expect in all 3 places.) But when I try to use `warble` then run the resulting jar I get the error "ignoring gem because its extensions are not built".

Thing is: this doesn't happen if I am packaging/running my app on my local machine, which is OS X El Capitan with `rvm`. When I check on my local machine, `$CLASSPATH` is populated with entries from `.rvm/gems/jruby-9.0.5.0/gems/my_custom_gem/vendor/jars` (which is what I expect, and what I need), but those aren't there on Alpine. The only other difference I saw was doing `ENV['GEM_PATH']` locally I see it pointing to `.rvm/gems/jruby-9.0.5.0` whereas on Alpine it is pointing to `uri:classloader:/`.

How is `$CLASSPATH` usually getting set inside a jar? Should I be seeing this `.rvm` dirs or not? How can I make sure a gem's vendored jars are available to something that uses that gem when it runs as a jar?

**Comment by mkristian** [comment]
if a packed jar/war files uses something from ```.rvm/gems/jruby-9.0.5.0``` then it is a clear sign that warbler does not isolate the packed jar/war enough from its environment. embedded jruby does have the same problem, especially with rvm.

something is populating the ```$CLASSPATH```, this happens either by ```$CLASSPATH << 'path/to/a/jar'``` or ```require 'path/to/a/jar'```. how does you gem with jar extension does populate those jars ?

are those jars packed inside you jar/war ?

**Comment by mooreniemi** [comment]
looks like the native extensions were a red herring. but yeah, a packed jar referencing stuff from .rvm seems Very Wrong. so perhaps really im seeing the _right_ behavior on alpine, and am not packing the jar right. i think i have a hunch, will report back. (and sorry again for cluttering up your issues with my questions)

**Comment by mkristian** [comment]
@mooreniemi you are most welcome with your questions, all this helps to keep improving things where you need to pack gems and jars

**Comment by mooreniemi** [comment]
thanks @mkristian -- very much appreciate your patience. the toughest thing for me so far is that all of the ruby logic that depends on file paths, globs, etc. won't work in the jar. i either have to conditionally add the app_name dir to everything only when i run in a jar, or... idk.

here's where i am currently stuck:
my gem takes some configuration from a host app that lists it as a dependency. one of these configuration settings is a manifest file (just a simple yaml). i have to configure my gem to boot differently depending on whether i am in a jar or not. the manifest lives at `host_app/app/manifest.yaml` -- when i am running the jar from inside `host_app` (so like `java -jar dist/host_app.jar`) i am fine, because my gem code basically cheats by grabbing the manifest: `url = java.net.URL.new("file:#{File.expand_path(MyGem.configuration.manifest_path)}/")` (which is set to `app/`). but if i want to move `host_app.jar` into any other folder, i'd need to change the manifest_path to `host_app/app`.

**Comment by mkristian** [comment]
I am not sure, if I completely get your point. so with jruby we have a pseudo path ```uri:classloader://``` which is root of your classloader or your dist/host_app.jar and this works as long you do not use globs. all file and path operations work on those pseudo paths. if you need globs to work, that can be done as well.

you also can move you Dir.pwd to ```uri:classloader://```.

I thought packed jar with warbler do unpack itself into a /tmp directory and run from there ?

still need some more puzzle pieces ;)

**Comment by mooreniemi** [comment]
well, i'll tell you the constraints. i cant change where code my gem wraps looks for the manifest file. it will always call `.getResourceStream('manifest.yaml')` but i don't know how to pack that file into the jar at root. when i run warble, it will always be inside `app_name/manifest.yaml`. is there any way i can move this? any way i can adjust the classloader?

**Comment by mooreniemi** [comment]
https://gist.github.com/mooreniemi/f963f83b26ddad968a360002405a52bd i'd need line 7 to return the manifest resource. i figure if i can move the yaml file to the root of the generated jar from warbler this'd work

**Comment by mkristian** [comment]
@mooreniemi the jruby-gradle-plugin and jruby9-maven-plugin do pack the jar with the ruby application being at the root of the jar.

but with warbler I also have something for you, inside config/warble.rb:
 ```config.java_classes = FileList["manifest.yaml"]```
this packed the yaml file on root of the jar.

**Comment by mooreniemi** [comment]
This worked: `  config.pathmaps.application << "%{app_name/manifest.yaml,manifest.yaml}p"`

**Comment by mooreniemi** [comment]
@mkristian but now i am stuck here: https://github.com/jruby/jruby/issues/3904

**Comment by kares** [comment]
this turned out a bit of "all the issues I am facing" issue :) ... could we close (maybe use SO, mailing-list) ?

**Comment by mooreniemi** [comment]
@kares i always try the #jruby channel first -- but tbh it is hard to get knowledgable people in jruby helping, esp at the level i am working atm :c

**Comment by kares** [comment]
@mooreniemi fair enough. so the original issue is explained as RVM interference.
my perspective is that people expect too much detailed support to come along with OSS, I can only see a better outcome on both ends if the assumption was not there :8ball:

**Comment by mooreniemi** [comment]
@kares i'm trying not to be insulted by that comment. i expect even oss to provide documentation and apis that mean i dont need to crack them open via `bundle open` very often. for instance, where is pathmaps documented?

elsewhere, other jruby folks admit that mixing jars in as dependencies is not really standardized. if i can't expect support, then i really am better off rewriting myself, which would be a bummer.

**Comment by rcrews** [comment]
The problem is caused by the current value of `GEM_PATH`. If set incorrectly, you'll get
`    Ignoring [gem-name-version] because its extensions are not built. Try: gem pristine [gem-name-version]`
(though, for me, the program seems to run fine anyway). With RVM, this likely happens when you build your jar with one gemset in effect, and then run your jar from a different directory where another gemset is in effect. Eliminate the messages by unsetting `GEM_PATH` while running your foreign jar:

* Unset all environment variables while running your command using `env -i`:
`    env -i java -jar /jar/made/from/warbler/my.jar parameter1 parameter2`

* Unset a subset of environment variables with the non-POSIX `-u` param (works on macOS):
`    env -u GEM_PATH -u CLICOLOR ~/my.jar paramenter1`

If you're still getting the messages when `GEM_PATH` is unset, then you likely have a genuine problem with your gem installations. If your Alpine Linux box is a Docker image, see [How to use use Bundler with Docker](https://bundler.io/v2.1/guides/bundler_docker_guide.html). If you're using Heroku, see [how Ruby applications configure bundler with environment variables](https://devcenter.heroku.com/changelog-items/1930).

**Comment by headius** [comment]
> The problem is caused by the current value of GEM_PATH.

@rcrews @kares @mooreniemi I am unclear where the bug is. It does not seem to be a JRuby bug, but perhaps something can be fixed in warbler? Or is this a bug in RubyGems as I raised at rubygems/rubygems#3520?

It seems clear to me that something needs to be fixed, even if it is just a better error message somewhere.
