### ISSUE TITLE
Version issues JRuby/Warbler

### ISSUE THREAD

**Issue by SvenSchwarzweller1** [jruby/warbler#378]
Hello,

actually I am faced with an issues wrabbing a JRuby app into a .war file using warbler.
When I run 

> $ warble pluginize

in my home directory of the application, I get the error "Your Ruby version is 2.3.0, but your Gemfile specified 2.2.3"
So actually it is not possible for me to wrab the Jruby app into a .war file that can be deployed to e.g. a tomcat server.
Is there a configuration file where I can specify the ruby version for the gems or do I have to install an older JRuby version?

When I run 
> $ jruby -v
I get the message "jruby 9.1.0.0 (2.3.0) 2016-05-02 a633c63 Java HotSpot(TM) 64-Bit Server VM 25.91-b14 on 1.8.0_91-b14 +jit [linux-x86_64]"
warbler version is "warbler-2.0.1"

Thank you for your answer.

**Comment by kares** [comment]
seems like a generic bundler error - that being said you do not need `warble pluginize` just `warble`
