### ISSUE TITLE
Excluding public assets from the war

### ISSUE THREAD

**Issue by abiacco** [jruby/warbler#384]
I'm trying to exclude my digested files in public/assets from my war, because I serve them up in apache.

I tried adding "public/assets/**/*" to my config.excludes but that didn't seem to work, it still included them. Tried variations of it with no success.
I then tried a blank public_html config. i.e. config.public_html = FileList[]
And while that did exclude them, i got a behavior in the webapp where it was trying to request NON-digested assets instead, which is a no-go.

i'm using warbler 2.0.3, jruby 9.1.2.0, sprockets 2.12.4, sprockets-rails 2.3.3.

Any help is appreciated.

-Tony

**Comment by kares** [comment]
you need to have the manifest file still included (to be found by sprockets) to serve the digested assets
