### ISSUE TITLE
Is there a way to exclude from compilation

### ISSUE THREAD

**Issue by EugenMayer** [jruby/warbler#387]
when enabling gem compilation, there are a lot of problematic gems like erubis https://github.com/EugenMayer/erubis/commit/d34acfdb7399b64b69bdb8dfb85a596579b4d3cc
which is plain syntax error

or rails https://github.com/rails/rails/blob/master/activejob/lib/rails/generators/job/templates/job.rb
which is not a ruby file and is going to change in the future https://github.com/rails/rails/pull/23878

But still, can i enable compilation but exclude some .rb files of gems to be compiled or at least exclude gems as a unit??
##

**Comment by kares** [comment]
nope it's not supported atm. where happy to accept PR on the topic though ...

**Comment by EugenMayer** [comment]
Well i guess i am just to involved in other projects and not very keen in ruby/rails to be a good contributor, sorry.
