### ISSUE TITLE
Can't execute `rails console` from runnable war

### ISSUE THREAD

**Issue by jandillmann** [jruby/warbler#389]
I have a Rails application with a `config/warble.rb` containing the following configuration:

    config.features = %w(executable runnable compiled)
    config.executable = ["rake", "rails"]

Running `java -jar app.war -S rake -T` prints the output of all Rake tasks, but running `java -jar app.war -S rails c` gives the following error message:

    ERROR: java.lang.IllegalStateException: failed to locate gem executable: './META-INF/rails.rb'

Is this an error in my configuration or a bug in warble? What can I do to investigate?

Gem Versions are:

    rails (4.2.7)
    warbler (2.0.3)

Tested on:

    jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [darwin-x86_64]

**Comment by kares** [comment]
should be working if you update to >= **9.1.5.0** ... let us know otherwise, thanks!

**Comment by jandillmann** [comment]
yes, thanks, it works with JRuby 9.1.5.0 👍

**Comment by OpakAlex** [comment]
Ой хуйня же полная это все, чем вам ебанатам простой руби хуевый? что хуй растет больше от jruby?
