### ISSUE TITLE
Unable to run the class files using rails runner

### ISSUE THREAD

**Issue by sathya** [jruby/warbler#39]
When we create the class files using warbler (using  compiled feature) , we are unable to run the class files using rails runner command.

The Environment details:

Warbler (1.3.1)
rails (3.0.9)
Rake (0.8.7) 
Jruby-jars(1.6.3)
Rubyzip (0.9.4)
Jruby 1.6.3 (ruby-1.8.7-p330) (2011-07-07 965162f) (Java HotSpot(TM) Client VM 1.6.0_23) 

This is  the command we attempted to run:

jruby -S  script\rails runner <classfilename>

This is the output we are getting:
--------------------------------------------

NameError: undefined local variable or method `??' for main:Object
   (root) at config\hello.class:1
     eval at org/jruby/RubyKernel.java:1088
   (root) at c:/jruby-1.6.3/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/comm
ands/runner.rb:48
  require at org/jruby/RubyKernel.java:1038
   (root) at c:/jruby-1.6.3/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/comm
ands/runner.rb:39
  require at org/jruby/RubyKernel.java:1038
   (root) at script\rails:6

can you please help me out in this regard?

Thanks, sathya.

**Comment by kares** [comment]
old issue - should no longer be relevant under Warbler 1.4 + JRuby 1.7 ... let us know otherwise, thx!
