### ISSUE TITLE
jruby-jars version is different then build time jruby version

### ISSUE THREAD

**Issue by mengelhart** [jruby/warbler#396]
I've recently had to downgrade to jruby 9.0.5.0 for development due to other project conflicts with developer vagrant VM's (long story).    I noticed that when Warbler builds a WAR, it's internal gemspec points jruby-jars >= 9.0.0.0 which results in deployment of a WAR using Jruby 9.1.5.0 

While everything so far works when I deploy to QA environments, it doesn't leave a warm fuzzy feeling of developing and deploying on different versions of the JRuby runtime.   Is there some configuration parameter that can override this so we can either a) simply use the version of jruby-jars based on the version of jruby that warbler is running in (ideal) or b) set a configuration flag that specifies the jruby-jars version that you want to use.

I looked around at the configuration and didn't see anything that implied there was a way to make this work in my warbler.rb so I apologize in advance if this is already configurable.

**Comment by kares** [comment]
add `gem 'jruby-jars', JRUBY_VERSION` in the Gemfile and you'll always have the same version as locally.
