### ISSUE TITLE
Working directory changed to temp extracted directory

### ISSUE THREAD

**Issue by icy-arctic-fox** [jruby/warbler#399]
When running a standalone jar or war, the contents are extracted to a temp directory. The current working directory is changed to that directory.

I have a program that reads a configuration file from the working directory and also writes logs to a relative directory. Because the working directory is changed, the files and directories can't be found. I've done some investigating and can't find a way to retrieve the actual directory the jar/war was ran from.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39202980-working-directory-changed-to-temp-extracted-directory?utm_campaign=plugin&utm_content=tracker%2F136961&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F136961&utm_medium=issues&utm_source=github).

**Comment by kares** [comment]
.war .jar files are meant to be self-existent. if we did not change the WD other parts such as Bundler/Rails would fail. so you should not assume a working directory path e.g. use ENV or pass a System property with your configurations location.
