### ISSUE TITLE
page_cache_directory seems to be incorrect

### ISSUE THREAD

**Issue by shellac** [jruby/warbler#4]
I created a simple rails 3 test app 'pcheck' to reproduce the issue. It has one controller:

    caches_page :show
    
    def show
      @item=params[:id]
    end

 `rails server -e production` writes the files to the correct location, but in tomcat I find:

    Write page /Users/pldms/Development/Servers/apache-tomcat-6.0.29/webapps/pcheck/pcheck/items/45.html (5.0ms)

(note repeated app name in path)

Let me know if you have a problem reproducing it. I can supply the full application if needed. This is using warbler 1.2.1 and jruby 1.5.6.

**Comment by jkutner** [comment]
I'm closing this since we don't intend to support earlier that 3.1
