### ISSUE TITLE
Ruby version problems

### ISSUE THREAD

**Issue by stephenlawrence** [jruby/warbler#400]
My question is: Do I need to have my active ruby pointed at jruby?

My project is ruby 2.1.10 (Gemfile)

When I initially war 'warble war' it ran ok.

When I try to build an compiled war I got this:

> Your Ruby version is 2.3.1, but your Gemfile specified 2.1.10

So I thought hmm, why is it saying I am using ruby 2.3.1?

Updated my Gemfile to 2.3.1 and set my rbenv to 2.3.1 and get this:

```
$ warble war
warble aborted!
NameError: uninitialized constant Warbler::Jar::JRUBY_VERSION
.rbenv/versions/2.3.1/bin/warble:23:in `load'
.rbenv/versions/2.3.1/bin/warble:23:in `<main>'
Tasks: TOP => war:files
```

So I thought maybe I need to point my rbenv to jruby-9.1.5.0. When I point it there I cannot get 'bundle install' to work:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/kgio-2.9.3/ext/kgio
.rbenv/versions/jruby-9.1.5.0/bin/jruby -r
./siteconf20161117-17451-1f199mm.rb extconf.rb
checking for CLOCK_MONOTONIC in time.h... RuntimeError: The compiler failed to
generate an executable file.
You have to install development tools first.
```

I do have dev tools installed. 
Do I need to alter my project ruby version to use warbler?
Do I need to be pointed at jruby to use it?

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39324761-ruby-version-problems?utm_campaign=plugin&utm_content=tracker%2F136961&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F136961&utm_medium=issues&utm_source=github).

**Comment by kares** [comment]
you should always use JRuby to `warble` ... ideally the same one you're packing in (`gem 'jruby-jars'`).
the issue you've run into is a Bundler/Gem problem -> you need to be able to `bundle install` cleanly under JRuby first (Warbler detects Bunlder), otherwise there's not much sense in packing it all up ...
