### ISSUE TITLE
Add support for adding Servlet Context Listeners

### ISSUE THREAD

**Issue by rsov** [jruby/warbler#410]
Hello,

I'm using `Warbler 2.0.4`, with the warbler.rb config file. Wanted to add a custom context listener for tomcat. 
The only way I got it to work was to modify `@servlet_context_listeners` variable. 

Would it be possible to made a cleaner api for modifying it?

My current code:

````ruby
config.webxml.instance_variable_set(:@servlet_context_listeners, 
      [config.webxml.servlet_context_listener, 'org.traf.jruby.RakeServlet'])
````

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41283170-add-support-for-adding-servlet-context-listeners?utm_campaign=plugin&utm_content=tracker%2F136961&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F136961&utm_medium=issues&utm_source=github).

**Comment by kares** [comment]
`config.webxml.servlet_context_listeners << 'org.traf.jruby.Servlet'` should be fine in 2.0.5
