### ISSUE TITLE
How set package name for .war file?

### ISSUE THREAD

**Issue by sergio-fry** [jruby/warbler#411]
I am trying to build .war file from example Sinatra app. When .war file is build, I am trying to import this file into Netbeans project. But I can't do that because imported .war file has no package name. It is displayed as ```<default package>```.

Is it possible to set desired package name when building a .war file?

**Comment by rsov** [comment]
You can set it in the config file: 
```ruby 
Warbler::Config.new do |config|
  config.jar_name = 'custon_name'
end
```

**Comment by sergio-fry** [comment]
@rsov it changes a name for generated .jar file from default. Not package name.

BTW, my problem is solved. I tried to run rack application from JavaFX app that renders it inside webview. I've packed this .war file inside .jar and then started it with Jetty embed server using setWar.

If somebody is interested it can be found here:

**https://github.com/sergio-fry/jruby-rack-inside-javafx**
