### ISSUE TITLE
Bundler 'path' components are not fully supported

### ISSUE THREAD

**Issue by iluwatar** [jruby/warbler#412]
```warning: Bundler `path' components are not currently supported.```

This warning is produced by our build (https://github.com/ria-ee/X-Road/issues/18). What does it mean and how do we get rid of it?

**Comment by iluwatar** [comment]
The warning seems to be emitted from this line https://github.com/jruby/warbler/blob/master/lib/warbler/traits/bundler.rb#L70

**Comment by iluwatar** [comment]
Closed without any comments? :astonished:

**Comment by kares** [comment]
sorry, there was meant to be one.

the gist is theres nothing to be done here. relative paths are fully supported. absolute paths are against the fully packed .war deployment way.

the warning is legit!
