### ISSUE TITLE
Running jar results in opening IRB Session?

### ISSUE THREAD

**Issue by ilovemysillybanana** [jruby/warbler#413]
```
C:\Users\Jose\workspace\Ruby\gem_name (master)
λ java -jar gem_name.jar
FOOBAR
irb(main):001:0>
```

I would like the jar to execute and then finish, so all I'd see is FOOBAR but this thing opens new sessions. That doesn't seem right. The code is an empty gem module that just has a simple `puts "FOOBAR"` command inside it.

**Comment by kares** [comment]
unusual. there's likely some code triggering `require 'irb'` - maybe its Bundler due one of the gem deps

**Comment by ilovemysillybanana** [comment]
@kares You were right, it had that in the one of the files because I had just made the gem to test. Thanks. I'll close this issue out. Hopefully, it helps someone else in the future.
