### ISSUE TITLE
java.lang.IllegalStateException in BodyPartEntity getInputStream() using RESTful POST request

### ISSUE THREAD

**Issue by KrithikaKR17** [jruby/warbler#414]
Hello,

I am trying to download multiple attachments from an application (in Non-REST mode) and pass it on to another application (in REST mode) using FormDataMultiPart. I am facing an exception when I try to extract the input stream from BodyPartEntity on the REST based application side.
At first glance, it looks like the input stream in the MIMEParser of BodyPartEntity seems to be already parsed. Surprisingly this is working fine in the other way around (REST --> NON-REST mode data transfer). I am using mimepull version 1.9.3.

Kindly help me in resolving this issue.

Stacktrace is:

java.lang.IllegalStateException: No such MIME Part: Part=0:binary
        at org.jvnet.mimepull.DataHead.read(DataHead.java:145)
        at org.jvnet.mimepull.MIMEPart.read(MIMEPart.java:94)
        at org.glassfish.jersey.media.multipart.BodyPartEntity.getInputStream(BodyPartEntity.java:80)

The code to construct the inputStream and attach it to FormDataMultiPart:

for(int i = 0; i < attachments.length; i++) {
    InputStream inputStream = new FileInputStream(new File("sample.xml"));
    formDataMultiPart.field("files", inputStream, MediaType.TEXT_XML_TYPE);
}

The code to get the inputStream is:

List<FormDataBodyPart> bodyParts = attachments.getFields("files");
for(int i = 1; i < bodyParts.size(); i++) {
    BodyPartEntity bodyPartEntity = (BodyPartEntity) bodyParts.get(i).getEntity();
    InputStream is = bodyPartEntity.getInputStream();
}

**Comment by kares** [comment]
not sure how's Warbler involved in this - you might have missed something. 
minepull, jvnet are not to be found here ...
