### ISSUE TITLE
warbler with faye-websocket

### ISSUE THREAD

**Issue by rodolfospalenza** [jruby/warbler#416]
Hello,

I'm try configure a simple websocket application with faye-websocket gem and create a war with warbler. I can create a war file, connect with http, but when I try use websocket I receive this message:

```javascript
var scheme   = "ws://";
var uri = scheme + window.document.location.host;
var ws = new WebSocket(uri);

// WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: Unexpected response code: 500
```

I think that the problem is jetty configuration because when I try start with puma the application works.

This is my `warble.rb`. 

```ruby
Warbler::Config.new do |config|
  config.features = %w(executable)
  config.jar_name = 'foo'
end
```

Is it possible configure jetty to receive websocket connection?

Thanks.

**Comment by rodolfospalenza** [comment]
Hello,

I understand better the concept and use `config.features = %w(runnable)`. 
It's works for me.

**Comment by mskutin** [comment]
@rodolfospalenza got into this too, alas, your solution doesn't work for me 
```ruby
Warbler::Config.new do |config|
  config.features = %w(runnable executable)
  config.jar_name = "faye"
  config.jar_extension = "war"
end
```

**Comment by rodolfospalenza** [comment]
Hi @mskutin,

I used this stack https://github.com/rosenfeld/simple-jruby-rack-server to running a rake application and integrate with faye-websocket.
