### ISSUE TITLE
jar application exit/goes in a blink

### ISSUE THREAD

**Issue by neenujohnson** [jruby/warbler#422]
I have created .jar file using warbler. But when I try to run the .jar, application starts and exit in a blink. It seems application is not crashing as the log says got via java -jar MyApp.jar > log.txt. The test application is single class derived from JFrame with a color JPanel added.
Why the application doesn't stay, but exit. Can somebody help me on what I am missing. How I can track the issue?

**Comment by kares** [comment]
there's usually a need to have a swing loop running (checkout some swing guides) -> not a warbler issue.
