### ISSUE TITLE
Is possible to use JRuby command line arguments in a .jar?

### ISSUE THREAD

**Issue by bolandross** [jruby/warbler#426]
I am packaging my app with warbler to create a Java Jar file.
As far as I know, this bundles up JRuby with all my gem dependencies and then runs my script. Is there a way to specify command line arguments for this?

For example, I'd like to use the splash image feature of JRuby:
`jruby -J-splash:splash.png my_script-rb`

**Comment by JasonLunn** [comment]
I'm not sure about general purpose command line flags, but for the specific use case of the splash screen, does [specifying it in the JAR's manifest](https://docs.oracle.com/javase/7/docs/api/java/awt/SplashScreen.html) work for you?

**Comment by kares** [comment]
... also `-J-splash:splash.png` is just a Java frontending opt (`java -jar my.jar -splash:...` with the pack)
and as suggested above, if you'd like to avoid that providing a custom manifest file should do the trick.
