### ISSUE TITLE
'bundle exec warble' fails when warbler rake task support is added

### ISSUE THREAD

**Issue by anildigital** [jruby/warbler#49]
When I included following lines in Rakefile to enable 'rake war' command

<pre>
require 'warbler'
Warbler::Task.new
</pre>

<pre>rake war</pre>  just works fine. <br>

But 

'bundle exec warble' starts failing.

<pre>
bundle exec warble --trace
warble aborted!
undefined method `blame_file!' for java.lang.StackOverflowError:Java::JavaLang::StackOverflowError
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:230:in `load_dependency'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:227:in `load_dependency'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/warbler-1.3.2/lib/warbler/application.rb:58:in `load_project_rakefile'
org/jruby/RubyArray.java:1603:in `each'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/warbler-1.3.2/lib/warbler/application.rb:56:in `load_project_rakefile'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/warbler-1.3.2/lib/warbler.rb:25:in `project_application'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/warbler-1.3.2/lib/warbler/traits/rails.rb:27:in `before_configure'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/warbler-1.3.2/lib/warbler/traits.rb:28:in `before_configure'
org/jruby/RubyArray.java:1603:in `each'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/warbler-1.3.2/lib/warbler/traits.rb:28:in `before_configure'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/warbler-1.3.2/lib/warbler/config.rb:170:in `initialize'
(eval):5:in `initialize'
org/jruby/RubyKernel.java:1088:in `eval'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/warbler-1.3.2/lib/warbler/task.rb:46:in `initialize'
./rakefile:8:in `(root)'
org/jruby/RubyKernel.java:1063:in `load'
/Users/anil.wadghule/.rvm/gems/jruby-1.6.4/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
</pre>

**Comment by jkutner** [comment]
This is fixed with following environment:

```
$ jruby -v 
jruby 9.0.1.0 (2.2.2) 2015-09-02 583f336 Java HotSpot(TM) 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 [darwin-x86_64]

$ bundle version
Bundler version 1.10.6

﻿﻿$ gem list warbler

*** LOCAL GEMS ***

warbler (2.0.0.rc1)
```

Probably fixed in other versions too.
