### ISSUE TITLE
Allow newer versions of rubyzip

### ISSUE THREAD

**Issue by ioanatia** [jruby/warbler#490]
Because of https://github.com/rubyzip/rubyzip/issues/384 when rubyzip is one of the bundled gems, some anti-virus solutions will flag the package as a security issue.

The issue was fixed in [rubyzip 2.0.0](https://github.com/rubyzip/rubyzip/releases/tag/v2.0.0), however because warbler requires  rubyzip with `['~> 1.0', '< 1.4']`, upgrading rubyzip to a newer version is not an option AFAICS.

rubyzip is used in [ZipSupport](https://github.com/jruby/warbler/blob/master/lib/warbler/zip_support.rb) which looks like it should still work with the latest version of the gem.

In this case just relaxing the requirement in [warbler.gemspec](https://github.com/jruby/warbler/blob/9be1d0f64fab3a9043f728f6d8ba06b6f93b12a2/warbler.gemspec#L34) to allow for newer versions of `rubyzip` might suffice.

**Comment by olleolleolle** [comment]
This was the commit which introduced the limitation: https://github.com/jruby/warbler/pull/362

**Comment by olleolleolle** [comment]
Let's make an attempt! @ioanatia Would you like to offer a PR>

**Comment by ioanatia** [comment]
Sure, I can do that.

**Comment by headius** [comment]
Go for it! Thank you for reporting and attempting a PR!
