### ISSUE TITLE
Warble Compiled Class files not created

### ISSUE THREAD

**Issue by joekarl** [jruby/warbler#53]
I'm currently using warbler 1.3.3 from this commit, 89793c689751d93379d623efbc5a641aebd53cab . 
Windows xp 32bit
Jruby 1.6.4

I'm running 'bundle exec warble compiled war' and I get the correct .rb files (with the references to the class files) but I don't get the class files in my jar.

I've tried running 'bundle exec warble compiled' to just spit out the class files, but this doesn't create any classfiles either.

When I run with the --trace command, I get the big string telling me that it is deleting the .class files but as far as I can tell none of them are even being created. 

Any ideas?

**Comment by jkutner** [comment]
i can't reproduce this with the warbler 1.4.10 or 2.0.0.rc1.
