### ISSUE TITLE
There was an error in your Gemfile, and Bundler cannot continue.

### ISSUE THREAD

**Issue by masterkain** [jruby/warbler#84]
Using latest warbler from git I tried to warble a 3.2.2 Rails jRuby(-head) app, I then performed a deploy of the war to tomcat and I get this error:

```
INFO: Starting Servlet Engine: Apache Tomcat/7.0.26
17-mar-2012 5.18.02 org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /usr/local/Cellar/tomcat/7.0.26/libexec/webapps/rails.war
There was an error in your Gemfile, and Bundler cannot continue.
```

which does not tell me where the error is. Anyone seeing this  issue?

**Comment by jkutner** [comment]
Let us know if the provide suggestion does not resolve the issue and we'll reopen
