### ISSUE TITLE
Missing w0t file that makes no sense

### ISSUE THREAD

**Issue by ericanderson** [jruby/warbler#9]
When executing "warble":

    w0t (No such file or directory)
    /Users/ericanderson/.rvm/gems/jruby-1.5.5@jmetabamboo/gems/warbler-1.2.1/lib/warbler/war.rb:69:in `create'

jruby 1.5.5

gems installed:

    *** LOCAL GEMS ***

    abstract (1.0.0)
    actionmailer (3.0.3)
    actionpack (3.0.3)
    activemodel (3.0.3)
    activerecord (3.0.3)
    activerecord-jdbc-adapter (1.1.1)
    activeresource (3.0.3)
    activesupport (3.0.3)
    arel (2.0.7)
    bouncy-castle-java (1.5.0145.2)
    builder (2.1.2)
    bundler (1.0.0.rc.5)
    erubis (2.6.6)
    glassfish (1.0.3)
    haml (3.0.2)
    hpricot (0.8.2)
    httpclient (2.1.6)
    i18n (0.5.0)
    jdbc-mysql (5.1.13)
    jruby-jars (1.5.6)
    jruby-openssl (0.7.3)
    jruby-rack (1.0.5)
    json (1.4.3)
    mail (2.2.15)
    maruku (0.6.0)
    mime-types (1.16)
    polyglot (0.3.1)
    rack (1.2.1)
    rack-mount (0.6.13)
    rack-test (0.5.7)
    rails (3.0.3)
    railties (3.0.3)
    rake (0.8.7)
    rubyzip (0.9.4)
    syntax (1.0.0)
    thor (0.14.6)
    treetop (1.4.9)
    trinidad (1.0.5)
    trinidad_jars (1.0.0)
    tzinfo (0.3.24)
    warbler (1.2.1)
    will_paginate (3.0.pre)
    xmpp4r (0.5)

**Comment by jkutner** [comment]
I'm going to close this, but let me know if it needs reopening.
